### ISSUE TITLE
Fulcrum signature checking not working?

### ISSUE THREAD

**Issue by dipunm** [microbolt-guide/microbolt#1]
It looks like verifying the commit for fulcrum v1.10.0 is not working.

```sh
$ git verify-commit v1.10.0
gpg: Signature made Mon Mar  4 00:16:27 2024 GMT
gpg:                     using RSA key B5690EEEBB952194
gpg: Can't check signature: No public key
```

One commit before works:
```sh
$ git verify-commit v1.10.0~1
...
gpg:                    using DSA key D465......C02C
gpg: Good signature from "Calin Culianu (NilacTheGrim) <calin.culianu@gmail.com>" [unknown]
...
...
Primary key fingerprint: D465 ..... C02C
```

Not sure what changed for the last commit? It also works for the commit before that too `v1.10.0~2`

**Comment by cculianu** [comment]
This is because v1.10.0 was the result of a github merge.  It was signed by github, I guess, and not by me.

**Comment by dipunm** [comment]
I suppose then that we need a more robust way to confirm that the commit is safe, we so far have an endorsement, by the author, but if future commits may be signed by different keys, then I'm not sure if it makes sense to add this secondary key to our list of trusted keys?

The source code can also be downloaded from the release page, but the `Fulcrum-VERSION-shasums.txt` does not include the hash for that file.

@cculianu would you consider adding the source code zip(s) to your shasums file which you already sign as part of your release process?

**Comment by cculianu** [comment]
There are multiple authors to any piece of software, and multiple keys may sign individual commits. This is not unique to Fulcrum...

> @cculianu would you consider adding the source code zip(s) to your shasums file which you already sign as part of your release process?

Yes that's not a bad idea. I can prepare a source tarball along with the release. It hadn't occurred to me to do that up until now. Should I update the release on github to include a source tarball.. as well as update the shasums file now?

**Comment by dipunm** [comment]
That would be great, then I could make a PR to update this guide and hopefully the maintainer will update 👍

**Comment by cculianu** [comment]
Ok, done: https://github.com/cculianu/Fulcrum/releases/tag/v1.10.0

I uploaded the new -src.tar.gz, and updated the shasums.txt and re-signed the shasums.txt file...

**Comment by doitwithnotepad** [comment]
Thank you for opening this first issue 🎉. Now I see that it was successfully resolved and that there is a newer version, I will update the guide and proceed to close this issue.
